on:
  workflow_call:

env:
  # This is the job id at line 5 from testprenvironment.yaml. If that job id changes, you'll need to update this value
  RW_PRENV_JOBID: 'TestPrEnvironment'
  CW_PRENV_JOBID: 'TestPrEnv-CW'
jobs:
  create-auto-pr:
    name: "Creates an auto merging PR when the branch is updated"
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'platformsh-templates' }}
    steps:
      - name: 'Prep Default Status Checks'
        id: prep_default_sc
        run: |
          userJobID=${{ vars.CW_JOBID }}
          envJobID=${{ env.CW_PRENV_JOBID }}
          echo "defaultStatusCheck=${userJobID:-${envJobID}} / ${{ env.RW_PRENV_JOBID }}" >> $GITHUB_OUTPUT
      - name: 'Prep Status Checks'
        id: prep_status_check
        run: |
          # get the value the user might have passed in to override ALL defaults
          userStatusCheck=${{ vars.STATUS_CHECKS }}
          # now get our "default" that takes any updated calling workflow job id and prepends it the the testprenvironment job id
          defaultStatusCheck="${{ steps.prep_default_sc.outputs.defaultStatusCheck }}"
          # if they actually gave us something, use it; otherwise use our default
          echo "statusCheck=${userStatusCheck:-${defaultStatusCheck}}" >> $GITHUB_OUTPUT
      - name: 'Prep the repo for autoPR'
        id: prepautopr
        uses: platformsh/gha-prep-for-autopr@main
        with:
          github-token: ${{ secrets.TEMPLATES_GITHUB_TOKEN }}
          status-checks: ${{ steps.prep_status_check.outputs.statusCheck }}

      - name: 'Create & merge PR'
        id: create-merge-pr
        uses: platformsh/gha-create-autopr@main
        with:
          github-token: ${{ secrets.TEMPLATES_GITHUB_TOKEN }}
          trigger-source: 'auto push'
          default-branch: ${{ steps.prepautopr.outputs.default-branch }}
          delete-branch-after-merge: 'yes'
