on:
  workflow_call:

jobs:
  record-rate:
    name: Record current rate limits
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'platformsh-templates' }}
    env:
      GH_TOKEN: ${{ secrets.TEMPLATES_GITHUB_TOKEN }}
    steps:
      - name: Current rate limits
        run: |
          curdate=$(date)
          echo "::notice::Current rate limits as of ${curdate}"
          gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /rate_limit | jq
  run_dm_update:
    name: Trigger Source Op
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'platformsh-templates' }}
    steps:
      - name: 'Run source ops with alt branch'
        if: ${{ vars.SOP_UPDATE_BRANCH != '' }}
        id: run-source-op-alt-branch
        uses: platformsh/gha-run-sourceops-update@main
        with:
          github_token: ${{ secrets.TEMPLATES_GITHUB_TOKEN }}
          platformsh_token: ${{ secrets.TEMPLATES_CLI_TOKEN }}
          update_branch_name: ${{ vars.SOP_UPDATE_BRANCH }}
      - name: 'Run source ops with default branch'
        if: ${{ vars.SOP_UPDATE_BRANCH == '' }}
        id: run-source-op
        uses: platformsh/gha-run-sourceops-update@main
        with:
          github_token: ${{ secrets.TEMPLATES_GITHUB_TOKEN }}
          platformsh_token: ${{ secrets.TEMPLATES_CLI_TOKEN }}