on:
  workflow_call:
#    secrets:
#     # The calling workflow should use `inherit` so we shouldnt need to specify the individual secrets here
#      TEMPLATES_GITHUB_TOKEN:
#        required: true
#      TEMPLATES_CLI_TOKEN:
#        required: true

jobs:
  test-pr-env:
    name: TestPrEnvironment
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'platformsh-templates' && github.event.pull_request.draft == false }}
    steps:
      - name: 'Do I have the token?'
        shell: bash
        run: |
          echo "Do I have the secret?"
          if [[ -z "${{ secrets.TEMPLATES_GITHUB_TOKEN }}" ]]; then
            echo "the GH token from secrets is not available."
          else
            printf "We should have the gh token: %s\n" "${{ secrets.TEMPLATES_GITHUB_TOKEN }}"
          fi
      - name: 'Get Project ID'
        id: 'get-proj-id'
        uses: platformsh/gha-retrieve-projectid@main
        with:
          github_token: ${{ secrets.TEMPLATES_GITHUB_TOKEN }}
        secrets: inherit

      - name: 'Get Production URL'
        id: 'get-prod-url'
        uses: platformsh/gha-retrieve-production-url@main
        with:
          platformsh_token: ${{ secrets.TEMPLATES_CLI_TOKEN }}
          project_id: ${{ steps.get-proj-id.outputs.project_id }}

      - name: 'Run Pull Request Tests'
        id: get-target-url
        uses: platformsh/gha-template-pr-tests@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          baseline-url: ${{ steps.get-prod-url.outputs.production_url }}