on:
  workflow_call:

jobs:
  # !!!! WARNING !!!!
  # If for some reason this job id needs to change, you'll need to update the value for env:RW_PRENV_JOBID in autopr.yaml
  TestPrEnvironment:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'platformsh-templates' && github.event.pull_request.draft == false }}
    steps:
      - name: 'Get Project ID'
        id: 'get-proj-id'
        uses: platformsh/gha-retrieve-projectid@main
        with:
          github_token: ${{ secrets.TEMPLATES_GITHUB_TOKEN }}
          
      - name: 'Get Production URL'
        id: 'get-prod-url'
        uses: platformsh/gha-retrieve-production-url@main
        with:
          platformsh_token: ${{ secrets.TEMPLATES_CLI_TOKEN }}
          project_id: ${{ steps.get-proj-id.outputs.project_id }}

      - name: 'Run Pull Request Tests'
        id: get-target-url
        uses: platformsh/gha-template-pr-tests@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          baseline-url: ${{ steps.get-prod-url.outputs.production_url }}
          delay-start: ${{ vars.DELAY_START }}